name: Continuous Delivery

on: workflow_dispatch

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Build & Deploy

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Setup pages
        run: actions/configure-pages@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist

      - name: Deploy application
        id: deployment
        uses: actions/deploy-pages@v2
